// app.js - client-side image -> gcode generator and preview

const fileInput = document.getElementById('file');
const generateBtn = document.getElementById('generate');
const downloadBtn = document.getElementById('download');
const clearBtn = document.getElementById('clear');

const widthMmInput = document.getElementById('widthMm');
const stepMmInput = document.getElementById('stepMm');
const thresholdInput = document.getElementById('threshold');
const invertInput = document.getElementById('invert');
const feedInput = document.getElementById('feed');
const penUpInput = document.getElementById('penUp');
const penDownInput = document.getElementById('penDown');
const serpentineInput = document.getElementById('serpentine');

const gcodeArea = document.getElementById('gcode');
const previewCanvas = document.getElementById('preview');
const previewCtx = previewCanvas.getContext('2d');

let loadedImage = null;

fileInput.addEventListener('change', async (e) => {
  const f = e.target.files[0];
  if (!f) return;
  const img = new Image();
  img.onload = () => {
    loadedImage = img;
    drawPreviewPlaceholder(img);
  };
  img.src = URL.createObjectURL(f);
});

clearBtn.addEventListener('click', () => {
  gcodeArea.value = '';
  previewCtx.clearRect(0,0,previewCanvas.width, previewCanvas.height);
  fileInput.value = '';
  loadedImage = null;
  downloadBtn.disabled = true;
});

generateBtn.addEventListener('click', () => {
  if (!loadedImage) {
    alert('Please choose an image first.');
    return;
  }
  const widthMm = parseFloat(widthMmInput.value);
  const stepMm = parseFloat(stepMmInput.value);
  const threshold = parseInt(thresholdInput.value);
  const invert = invertInput.checked;
  const feed = parseFloat(feedInput.value);
  const penUpZ = parseFloat(penUpInput.value);
  const penDownZ = parseFloat(penDownInput.value);
  const serpentine = serpentineInput.checked;

  const pixelWidth = Math.max(1, Math.round(widthMm / stepMm));
  const scale = pixelWidth / loadedImage.width;
  const pixelHeight = Math.max(1, Math.round(loadedImage.height * scale));

  // draw to offscreen canvas to get pixel data at desired resolution
  const off = document.createElement('canvas');
  off.width = pixelWidth;
  off.height = pixelHeight;
  const octx = off.getContext('2d');
  // draw with smoothing disabled for crisp sampling
  octx.imageSmoothingEnabled = false;
  octx.fillStyle = '#ffffff';
  octx.fillRect(0,0,off.width, off.height);
  octx.drawImage(loadedImage, 0, 0, off.width, off.height);

  const imgData = octx.getImageData(0,0,off.width, off.height).data;

  // Build binary matrix: true = draw
  const drawMatrix = new Array(off.height);
  for (let y=0;y<off.height;y++){
    drawMatrix[y] = new Array(off.width);
    for (let x=0;x<off.width;x++){
      const idx = (y*off.width + x)*4;
      const r = imgData[idx], g = imgData[idx+1], b = imgData[idx+2];
      // luminance
      const lum = 0.299*r + 0.587*g + 0.114*b;
      const isDark = lum < threshold;
      drawMatrix[y][x] = invert ? !isDark : isDark;
    }
  }

  // Generate G-code by scanning rows
  const lines = [];
  const fileHeader = [
    `; Generated by Image→Gcode Plotter`,
    `; image size: ${off.width} x ${off.height} px`,
    `G21 ; units mm`,
    `G90 ; absolute`,
    `G0 Z${penUpZ.toFixed(3)} F${feed}`,
    ``
  ];
  lines.push(...fileHeader);

  function moveRapid(x, y){
    return `G0 X${x.toFixed(3)} Y${y.toFixed(3)} F${feed}`;
  }
  function plunge(z){
    return `G1 Z${z.toFixed(3)} F${feed}`;
  }
  function drawTo(x, y){
    return `G1 X${x.toFixed(3)} Y${y.toFixed(3)} F${feed}`;
  }

  // Y grows positive downward here (image top-left = 0,0). Many machines use bottom-left origin.
  // You can flip Y by replacing y_mm = (off.height - 1 - y) * stepMm
  for (let row=0; row<off.height; row++){
    const y = serpentine && (row % 2 === 1) ? (off.height - 1 - row) : row; // if serpentine, we reverse row order for alternate direction only visually for scanning; actual drawing below covers direction per variable below
    const actualY = row;
    const y_mm = actualY * stepMm;
    // decide scanning direction for serpentine
    const leftToRight = !serpentine || (row % 2 === 0);
    const xStart = leftToRight ? 0 : off.width - 1;
    const xEnd = leftToRight ? off.width - 1 : 0;
    const step = leftToRight ? 1 : -1;

    let x = xStart;
    while ((leftToRight && x <= xEnd) || (!leftToRight && x >= xEnd)){
      // find next draw pixel
      let found = false;
      let segStart = x;
      while ((leftToRight && segStart <= xEnd) || (!leftToRight && segStart >= xEnd)){
        if (drawMatrix[actualY][segStart]){
          found = true;
          break;
        }
        segStart += step;
      }
      if (!found) break;
      // find segEnd
      let segEnd = segStart;
      let next = segEnd + step;
      while ((leftToRight && next <= xEnd) || (!leftToRight && next >= xEnd)){
        if (!drawMatrix[actualY][next]) break;
        segEnd = next;
        next += step;
      }

      // convert to mm coordinates
      const x0_mm = Math.min(segStart, segEnd) * stepMm;
      const x1_mm = (Math.max(segStart, segEnd)+1) * stepMm; // +1 to include full pixel width
      // Move rapid (pen up) to start
      lines.push(`; row ${actualY} segment ${segStart}..${segEnd}`);
      lines.push(moveRapid(x0_mm, y_mm));
      lines.push(plunge(penDownZ));
      lines.push(drawTo(x1_mm, y_mm));
      lines.push(plunge(penUpZ));

      // continue scanning after segment
      x = segEnd + step;
    }
  }

  lines.push('');
  lines.push('G0 Z' + penUpZ.toFixed(3));
  lines.push('; End of file');

  const gcodeText = lines.join('\n');
  gcodeArea.value = gcodeText;
  downloadBtn.disabled = false;

  // Render preview: draw white bg and black pixels for segments
  renderPreview(drawMatrix, stepMm);

  // Attach the gcode for download via blob
  downloadBtn.onclick = () => {
    const blob = new Blob([gcodeText], {type:'text/plain'});
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'image_plot.gcode';
    document.body.appendChild(a);
    a.click();
    a.remove();
    URL.revokeObjectURL(url);
  };
});

function drawPreviewPlaceholder(img){
  // Fit the preview canvas to image aspect ratio
  const maxW = previewCanvas.width;
  const maxH = previewCanvas.height;
  // scale preview canvas to maintain aspect ratio
  previewCtx.clearRect(0,0,previewCanvas.width, previewCanvas.height);
  // Draw scaled image into preview
  const scale = Math.min(previewCanvas.width / img.width, previewCanvas.height / img.height);
  const w = img.width * scale, h = img.height * scale;
  previewCtx.fillStyle = '#fff';
  previewCtx.fillRect(0,0,previewCanvas.width, previewCanvas.height);
  previewCtx.drawImage(img, 0, 0, img.width, img.height,
    (previewCanvas.width-w)/2, (previewCanvas.height-h)/2, w, h);
}

function renderPreview(drawMatrix, stepMm){
  // paint preview canvas sized to matrix but scaled to fit element
  const pxW = drawMatrix[0].length;
  const pxH = drawMatrix.length;
  // set an internal temp canvas to draw 1:1
  const tmp = document.createElement('canvas');
  tmp.width = pxW;
  tmp.height = pxH;
  const tctx = tmp.getContext('2d');
  const img = tctx.createImageData(pxW, pxH);
  for (let y=0;y<pxH;y++){
    for (let x=0;x<pxW;x++){
      const idx = (y*pxW + x)*4;
      const val = drawMatrix[y][x] ? 0 : 255;
      img.data[idx] = val;
      img.data[idx+1] = val;
      img.data[idx+2] = val;
      img.data[idx+3] = 255;
    }
  }
  tctx.putImageData(img, 0, 0);

  // now draw scaled to preview canvas, preserving aspect ratio
  const w = previewCanvas.width;
  const h = previewCanvas.height;
  previewCtx.fillStyle = '#fff';
  previewCtx.fillRect(0,0,w,h);

  const scale = Math.min(w/pxW, h/pxH);
  const drawW = pxW * scale;
  const drawH = pxH * scale;
  previewCtx.imageSmoothingEnabled = false;
  previewCtx.drawImage(tmp, 0, 0, pxW, pxH, (w-drawW)/2, (h-drawH)/2, drawW, drawH);
}